name: Deploy to Railway

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4 # Mise à jour vers v4

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Mise à jour vers v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Mise à jour vers v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Mise à jour vers v5
        with:
          context: .
          push: true
          tags: carellihoula10/football_bundesliga

      # Install Railway CLI
      - name: Install Railway CLI
        run: |
          curl -sSL https://railway.app/install.sh | bash
          echo "${HOME}/.railway/bin" >> $GITHUB_PATH

      # 6. Déploiement direct sur Railway sans `railway link`
      - name: Deploy to Railway
        env:
          RAILWAY_API_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: |
          railway up --ci -- --project ${{ secrets.RAILWAY_PROJECT_ID }} --service tranquil-achievement --environment production
g